# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
    
    # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

fibsum <- function(fib, limit, sum=0, i=2) {
    while(sum < limit) {
        i = i + 1
        # cat('This is ', i, '. run\n')
        # cat('----------------------\n')
        x <- fib[length(fib)-1]
        y <- fib[length(fib)]
        # cat('x=', fib[length(fib)-1], ' y=', y, ' prevsum=', sum, ' limit=', limit, '\n')
        sum <- x + y
        # cat('sum=', sum, '\n\n')
        if (sum < limit) fib[i] <- sum
        # cat('fib', fib, '\n')
    }
    return(fib)
}

fib <- fibsum(fib=c(1, 1), limit=4000000)
sum(fib[which(fib[]%%2==0)])
